version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_fortify
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: fortify_db
      MYSQL_USER: allara1
      MYSQL_PASSWORD: allara1@espe.edu.ec
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - fortify_net

volumes:
  mysql_data:

networks:
  fortify_net:
